create view TEMP_CURRENCIES as
SELECT
            currency_id,
            currency,
            usd_conversion
        FROM
            currencies
        WHERE
            UPPER(currency) LIKE '%%'
/

INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (1, 'USD', 1.02);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (2, 'EUR', 0.85);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (3, 'GBP', 22.01);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (4, 'JPY', 110);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (5, 'CAD', 1.25);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (6, 'AUD', 1.3);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (7, 'CHF', 0.9);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (8, 'CNY', 6.5);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (9, 'INR', 75);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (10, 'RUB', 75);
INSERT INTO HR.TEMP_CURRENCIES (CURRENCY_ID, CURRENCY, USD_CONVERSION) VALUES (11, 'BTC', 52654.3468);
